# Generated by Django 4.2 on 2023-05-08 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kobosh", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="kobosh_prod_id_15bd1a_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="kobosh_prod_name_d21d40_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="kobosh_prod_created_1e9941_idx",
        ),
    ]
