# Generated by Django 4.2 on 2023-05-08 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kobosh", "0002_alter_product_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
