# Generated by Django 4.2 on 2023-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kobosh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="products//%Y/%m/%d"),
        ),
    ]
